### ISSUE TITLE
Mirror two LRS 200 Mount parts

### ISSUE THREAD

**Issue by AdronTech** [MagicPhoenix/MPX-VORON-24R2-CBT#1]
Instead of printing the mount 4x, you have to print it 2x like it is provided and 2x mirrored.
Else the LRS is not mountable (at least in my case, as the mount is non symetrical)

Parts in question:
[Elec_LRS_200_Mount_x4.STL](https://github.com/MagicPhoenix/MPX-VORON-24R2-CBT/blob/main/Printed%20Parts/Elec_LRS_200_Mount_x4.STL)

**Comment by Livezxy** [comment]
You just need to flip the mount part, they are designed to use the same part,  there'a a section in our wiki: https://mpx.wiki/assembly-tips-tricks#lrs-200-24
